import { Gallery } from '@/types'

export const galleries: Gallery[] = [
  {
    id: 1,
    title: 'Hole Repairs',
    description: 'Expert drywall hole repair and patch work, making your walls look like new again',
    imageUrl: '/patchwork/images/hole_repairs/hole1_after.jpg',
    slug: 'hole-repairs',
    images: [
      {
        id: 1,
        title: 'Large Wall Repair',
        beforeImage: '/patchwork/images/hole_repairs/hole1_before.jpg',
        afterImage: '/patchwork/images/hole_repairs/hole1_after.jpg',
        description: 'Professional repair of a large wall damage',
      },
      {
        id: 2,
        title: 'Water Damage Repair',
        beforeImage: '/patchwork/images/hole_repairs/hole3_before.jpg',
        afterImage: '/patchwork/images/hole_repairs/hole3_after.jpg',
        description: 'Seamless repair of water damage',
      },
      {
        id: 3,
        title: 'Large Hole Repair',
        beforeImage: '/patchwork/images/hole_repairs/hole4_before.jpg',
        afterImage: '/patchwork/images/hole_repairs/hole4_after.jpg',
        description: 'Seamless repair of large wall damage',
      },
      {
        id: 4,
        title: 'Wall Section Repair',
        beforeImage: '/patchwork/images/hole_repairs/hole5_before.jpg',
        afterImage: '/patchwork/images/hole_repairs/hole5_after.jpg',
        description: 'Professional repair of complex wall damage',
      },
      {
        id: 5,
        title: 'Repair around outlets',
        beforeImage: '/patchwork/images/hole_repairs/hole6_before.jpg',
        afterImage: '/patchwork/images/hole_repairs/hole6_after.jpg',
        description: 'Seamless repair of wall damage around outlets',
      },
      {
        id: 6,
        title: 'Retouch',
        beforeImage: '/patchwork/images/hole_repairs/hole7_before.jpg',
        afterImage: '/patchwork/images/hole_repairs/hole_7after.jpg',
        description: 'Retouching of wall damage',
      },
      {
        id: 7,
        title: 'Small Hole Repair',
        beforeImage: '/patchwork/images/hole_repairs/hole8_before.jpg',
        afterImage: '/patchwork/images/hole_repairs/hole8_after.jpg',
        description: 'Seamless repair of small wall damage',
      },
      {
        id: 8,
        title: 'Corner Damage Repair',
        beforeImage: '/patchwork/images/hole_repairs/hole2_before.jpg',
        afterImage: '/patchwork/images/hole_repairs/hole2_after.jpg',
        description: 'Expert repair of corner wall damage',
      },
      {
        id: 9,
        title: 'Detailed Wall Repair',
        beforeImage: '/patchwork/images/hole_repairs/hole9_before.jfif',
        afterImage: '/patchwork/images/hole_repairs/hole9_after.jfif',
        description: 'Detailed repair work with perfect finishing',
      },
    ],
  },
  {
    id: 2,
    title: 'Texture Work',
    description: 'Custom texture finishes to match your existing walls or create a new look',
    imageUrl: '',
    slug: 'texture-work',
    images: [],
  },
  {
    id: 3,
    title: 'Finishing Work',
    description: 'Professional drywall finishing and detailing for a flawless look',
    imageUrl: '',
    slug: 'finishing',
    images: [],
  },
  {
    id: 4,
    title: 'Carpentry',
    description: 'Custom carpentry solutions including framing, trim work, and wood repairs',
    imageUrl: '/patchwork/images/carpentry/carpentry1_after.jpg',
    slug: 'carpentry',
    images: [
      {
        id: 1,
        title: 'Custom Closet Installation',
        beforeImage: '/patchwork/images/carpentry/carpentry1_before.jpg',
        afterImage: '/patchwork/images/carpentry/carpentry1_after.jpg',
        description: 'Installation of custom closet',
      },
      {
        id: 2,
        title: 'Window Frame Repair',
        beforeImage: '/patchwork/images/carpentry/carpentry2_before.jpg',
        afterImage: '/patchwork/images/carpentry/carpentry2_after.jpg',
        description: 'Professional window frame repair and restoration',
      },
      {
        id: 3,
        title: 'Custom Finishing on Wood',
        beforeImage: '/patchwork/images/carpentry/carpentry3_before.jpg',
        afterImage: '/patchwork/images/carpentry/carpentry3_after.jpg',
        description: 'Custom finishing on wood',
      },
      {
        id: 4,
        title: 'Custom Storage Installation',
        beforeImage: '/patchwork/images/carpentry/carpentry4_before.jfif',
        afterImage: '/patchwork/images/carpentry/carpentry4_after.jpeg',
        description: 'Custom installation of bathroom storage',
      },
      {
        id: 5,
        title: 'Closet Door Installation',
        beforeImage: '/patchwork/images/carpentry/carpentry5_before.jpg',
        afterImage: '/patchwork/images/carpentry/carpentry5_after.jpg',
        description: 'Expert installation of closet doors',
      },
      {
        id: 6,
        title: 'Baseboard Repair',
        beforeImage: '/patchwork/images/carpentry/carpentry6_before.jpg',
        afterImage: '/patchwork/images/carpentry/carpentry6_after.jpg',
        description: 'Baseboard repair and restoration',
      },
      {
        id: 7,
        title: 'Cabinet Repair',
        beforeImage: '/patchwork/images/carpentry/carpentry7_before.jpg',
        afterImage: '/patchwork/images/carpentry/carpentry7_after.jpg',
        description: 'Cabinet repair and restoration of sink cabinet',
      },
      {
        id: 8,
        title: 'Wainscoting',
        beforeImage: '/patchwork/images/carpentry/carpentry8_before.jpg',
        afterImage: '/patchwork/images/carpentry/carpentry8_after.jpg',
        description: 'Professional raised panel wainscoting addition',
      },
      {
        id: 9,
        title: 'Decorative Trim',
        beforeImage: '/patchwork/images/carpentry/carpentry9_before.jpg',
        afterImage: '/patchwork/images/carpentry/carpentry9_after.jpg',
        description: 'Expert decorative ceiling trim installation',
      },
      {
        id: 10,
        title: 'Baseboard Repair',
        beforeImage: '/patchwork/images/carpentry/carpentry10_before.jpg',
        afterImage: '/patchwork/images/carpentry/carpentry10_after.jpg',
        description: 'Baseboard repair and restoration',
      },
      {
        id: 11,
        title: 'Attic Door Restoration',
        beforeImage: '/patchwork/images/carpentry/carpentry11_before.jpg',
        afterImage: '/patchwork/images/carpentry/carpentry11_after.jpg',
        description: 'Professional attic door restoration',
      }
    ],
  },
] 